# Standard Precipitation Evapotranspiration Index {#spei}

*Authors: Author 1, Author 2*

*Supervisor: Henri Funk*

## Definition

The SPEI is a statistical indicator that shows dry and wet periods on the basis of the climatic water balance (total precipitation minus total potential evaporation). It captures water deficits or surpluses on the land surface better than the Standardised Precipitation Index (SPI), which focuses solely on precipitation. The example shown below is based on a time series created from measured monthly precipitation totals for the years 1961 to 2016 and calculated potential evaporation amounts for the same period. The potential evaporation is based on the so-called FAO grass evaporation, which takes into account radiation, air temperature, relative humidity and wind speed over a standard grass area. The time series is broken down into 12 monthly frequency sums, to each of which a cumulative log-logistic distribution is fitted. This is transformed into a corresponding cumulative standard normal distribution, the abscissa value of which - referred to as SPEI - allows simple assignment to probability classes.
@vicente

## Methods

- Distributions and Quantiles

